/**********************************************************************
 * Extern for Scribl
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var Scribl = {
  "constructor": {
    "constructor": function () {},
    "extend": function () {}
  },
  "extend": function () {}
};
Scribl.prototype = {
  "init": function () {},
  "getScaleHeight": function () {},
  "getHeight": function () {},
  "getFeatures": function () {},
  "setCanvas": function () {},
  "addScale": function () {},
  "addTrack": function () {},
  "removeTrack": function () {},
  "loadGenbank": function () {},
  "loadBed": function () {},
  "loadBam": function () {},
  "loadFeatures": function () {},
  "addGene": function () {},
  "addProtein": function () {},
  "addFeature": function () {},
  "slice": function () {},
  "draw": function () {},
  "redraw": function () {},
  "initScale": function () {},
  "drawScale": function () {},
  "pixelsToNts": function () {},
  "ntsToPixels": function () {},
  "initScrollable": function () {},
  "determineMajorTick": function () {},
  "getTickText": function () {},
  "getTickTextDecimalPlaces": function () {},
  "handleMouseEvent": function () {},
  "addClickEventListener": function () {},
  "addMouseoverEventListener": function () {},
  "removeEventListeners": function () {},
  "registerEventListeners": function () {}
};
Scribl.constructor.prototype = {
  "init": function () {},
  "getScaleHeight": function () {},
  "getHeight": function () {},
  "getFeatures": function () {},
  "setCanvas": function () {},
  "addScale": function () {},
  "addTrack": function () {},
  "removeTrack": function () {},
  "loadGenbank": function () {},
  "loadBed": function () {},
  "loadBam": function () {},
  "loadFeatures": function () {},
  "addGene": function () {},
  "addProtein": function () {},
  "addFeature": function () {},
  "slice": function () {},
  "draw": function () {},
  "redraw": function () {},
  "initScale": function () {},
  "drawScale": function () {},
  "pixelsToNts": function () {},
  "ntsToPixels": function () {},
  "initScrollable": function () {},
  "determineMajorTick": function () {},
  "getTickText": function () {},
  "getTickTextDecimalPlaces": function () {},
  "handleMouseEvent": function () {},
  "addClickEventListener": function () {},
  "addMouseoverEventListener": function () {},
  "removeEventListeners": function () {},
  "registerEventListeners": function () {}
};
/**********************************************************************
 * End Generated Extern for Scribl
/**********************************************************************/